name: Feature request
description: Suggest a feature
labels: ["T-feature"]
body:
  - type: markdown
    attributes:
      value: |
        Please ensure that the feature has not already been requested in the issue tracker.

        Additionally, make sure this is a feature request for *foundryup*.
        Feature requests for other Foundry tools should be created in their issue tracker.

        Thanks for helping us improve Foundry!
  - type: textarea
    attributes:
      label: Describe the feature you would like
      description: Please also describe what the feature is aiming to solve, if relevant.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context to the feature (like screenshots, resources)
